The neighborhood boundaries files on this site are derived from the original ESRI Shapefiles created by Zillow and available at

http://www.zillow.com/howto/api/neighborhood-boundaries.htm

Zillow have kindly made these available under a Creative Commons license (http://creativecommons.org/licenses/by-sa/3.0/).

This allows you to share and modify the data but you need to attribute Zillow and must distribute any derivative forms of the data under the same or similar licenses. Attribution should take the form of including their logo with a link back to their site.

I am not able to include that logo in this License file but the link is provided.

The derivative files here were generated by Robert Jones (jones@craic.com) and are distributed under the same terms.


